version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - apt-get update -y
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

  pre_build:
    commands:
      - cp .env.example .env
      - touch database/database.sqlite
      - composer install --no-dev --optimize-autoloader
      - php artisan key:generate
      - php artisan migrate
      - npm install
      - npm run build

  build:
    commands:
      - echo "Build phase complete."

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: .  # Ensures the entire Laravel app is uploaded as artifact